# Bailey Sweis 
## Week 11: 3/29/2022
### Python Numpy intro

In [1]:
import numpy as np

In [2]:
np._version__

AttributeError: module 'numpy' has no attribute '_version__'

In [3]:
np.__version__

'1.18.5'

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
print(arr)

[1 2 3 4 5 6]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr[2]

3

In [9]:
arr1 = np.array((1,2,3,4,5,6))

In [10]:
arr1[2]

3

In [11]:
#Dimesions in arrays
'''
0-D Arrays
'''
arr0 = np.array(50)
print(arr0)

50


In [12]:
arrr0

NameError: name 'arrr0' is not defined

In [13]:
arr0

array(50)

In [15]:
# 1-D array
# an array that has 0-D arrays as elements
arr1 = np.array([1,2,3,4,5,6,7,8])

In [16]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# 2-D array
# an array that has 1-D arrays as elements
arr2 = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])

In [18]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [19]:
arr2[1,2]

33

In [20]:
arr2[0,3]

4

In [22]:
# 3-D array
# an array that has 2-D arrays as elements
arr3 = np.array([[ [1,2,3], [4,5,6] ], [ [11,22,33], [44,55,66] ]])

In [23]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [24]:
arr3[0,1,1]

5

In [25]:
arr0.ndim

0

In [26]:
arr1.ndim

1

In [27]:
arr2.ndim

2

In [28]:
arr3.ndim

3

In [29]:
#create 4-D
arr4 = np.array([1,2,3,4,5], ndmin = 4)

In [30]:
arr4

array([[[[1, 2, 3, 4, 5]]]])

In [31]:
#create 5-D
arr5 = np.array([1,2,3,4,5], ndmin = 5)

In [32]:
arr5

array([[[[[1, 2, 3, 4, 5]]]]])

In [33]:
print(arr5)

[[[[[1 2 3 4 5]]]]]


In [34]:
arr4.ndim

4

In [35]:
arr5.ndim

5

In [36]:
#Array indexing
print(arr1)

[1 2 3 4 5 6 7 8]


In [37]:
arr1[2]

3

In [38]:
arr1[-1]

8

In [39]:
sum(arr1)

36

In [40]:
#2-D array access
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [42]:
arr2[1,4]

55

In [44]:
arr2[0,-1]

6

In [45]:
arr2[0,2]

3

In [46]:
arr2.shape

(2, 6)

In [47]:
arr3.shape

(2, 2, 3)

In [48]:
arr3[0,1,2]

6

In [49]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [50]:
arr3[1]

array([[11, 22, 33],
       [44, 55, 66]])

In [51]:
arr3[1,0,1]

22

In [52]:
arr3[0,0]

array([1, 2, 3])

In [53]:
arr3[1,0]

array([11, 22, 33])

In [54]:
arr3[1,1,1]

55

In [56]:
arr3[0,0,-1]

3

In [57]:
arr3.shape

(2, 2, 3)

In [58]:
#slicing np arrays
#1-D arrays 
'''
arr[start;stop]
Start: start index
End: stop index (exclusive)
Step: stride or jump, step is considered 1
'''
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [63]:
arr1[2:]

array([3, 4, 5, 6, 7, 8])

In [64]:
arr1[:5]

array([1, 2, 3, 4, 5])

In [66]:
arr1[-4:-1]

array([5, 6, 7])

In [68]:
arr1[1:6:2]

array([2, 4, 6])

In [69]:
#slicing 2-D arrays
arr2.shape

(2, 6)

In [70]:
arr2[0]

array([1, 2, 3, 4, 5, 6])

In [71]:
arr2[1]

array([11, 22, 33, 44, 55, 66])

In [72]:
arr2[0,5]

6

In [73]:
arr2[1,2:6]

array([33, 44, 55, 66])

In [74]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [75]:
arr2[0:2,1]

array([ 2, 22])

In [76]:
arr2[:,1]

array([ 2, 22])

In [78]:
arr2[:, 1:3]

array([[ 2,  3],
       [22, 33]])

In [79]:
arr2[1, 1:3]

array([22, 33])

In [80]:
arr2[:, -3:]

array([[ 4,  5,  6],
       [44, 55, 66]])

In [81]:
#slicing 3-D array
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [82]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])

In [83]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [85]:
arr3.shape

(2, 2, 3)

In [86]:
# [axis0, axis1, axis2]
arr3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [87]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr3[0,0]

array([1, 2, 3])

In [89]:
arr3[:, 0]

array([[1, 2, 3],
       [7, 8, 9]])

In [90]:
arr3[:,:,0]

array([[ 1,  4],
       [ 7, 10]])

In [91]:
arr3[:,0,-1]

array([3, 9])

In [92]:
arr3[:,:,-1]

array([[ 3,  6],
       [ 9, 12]])

In [93]:
arr3[1,:,-2:]

array([[ 8,  9],
       [11, 12]])