# Bailey Sweis
## week 12: 4/12/22
## numpyunfunc

In [1]:
import numpy as np

In [4]:
# descriptive stats measures
arr =np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print (arr.shape)

(3, 3)


In [5]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr.sum()

45

In [7]:
arr.sum(0)

array([12, 15, 18])

In [8]:
arr.sum(1)

array([ 6, 15, 24])

In [9]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [13]:
np.sum(arr, axis = None)

45

In [14]:
#mean()
arr.mean()

5.0

In [15]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr.mean(0)

array([4., 5., 6.])

In [18]:
arr.mean(1)

array([2., 5., 8.])

In [19]:
np.mean(arr, axis = 0)

array([4., 5., 6.])

In [20]:
arr.var()

6.666666666666667

In [21]:
arr.std()

2.581988897471611

In [22]:
arr = np.array([3,6,8,1,9,10,62,1,5,7,4,1,11,15,11,14])
arr.sort()

In [23]:
arr

array([ 1,  1,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11, 14, 15, 62])

In [25]:
#transpose
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [27]:
print(arr.shape)

(2, 4)


In [28]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [31]:
arr.transpose().shape

(4, 2)

In [32]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
arr.shape

(2, 4)

In [34]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [35]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [38]:
arr.shape

(2, 4)

In [40]:
arr.transpose((0,1)).shape

(2, 4)

In [41]:
arr.transpose((1,0)).shape

(4, 2)

In [44]:
sarr3 = np.arange(20).reshape((2,5,2))

In [45]:
sarr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [46]:
print(sarr3.shape)

(2, 5, 2)


In [47]:
sarr3.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [49]:
sarr3.transpose()


array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [50]:
sarr3.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [51]:
sarr3.transpose((1,0,2)).shape

(5, 2, 2)

In [53]:
sarr3.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [54]:
#random 
np.random.random((4,4)) #returns numbers between [0.0 - 0.99]

array([[0.87554818, 0.6703037 , 0.5113811 , 0.75792128],
       [0.8201462 , 0.71593804, 0.84496936, 0.18819698],
       [0.98527982, 0.57011843, 0.98665347, 0.97504382],
       [0.24409845, 0.42000367, 0.12594103, 0.39746747]])

In [55]:
from numpy.random import random as rand

In [56]:
rand((4,4))

array([[0.28329376, 0.53184133, 0.03764813, 0.4307901 ],
       [0.53964112, 0.70548553, 0.94125242, 0.49505321],
       [0.02982465, 0.38884059, 0.47430935, 0.07601517],
       [0.13834233, 0.73255229, 0.90347357, 0.16800294]])

In [58]:
from numpy.random import randn as ran
ran(5,5)

array([[ 0.25892555,  0.37988156,  0.07162563, -1.37545424, -0.2059427 ],
       [ 0.39371552,  0.94662931,  0.80614355,  0.73307746, -1.2473037 ],
       [ 2.06178353, -0.46232686,  1.81669642,  0.65039215,  0.38210934],
       [-1.02360809, -0.84790119, -0.63411968, -0.58918044, -0.69516312],
       [ 0.7289322 ,  0.75147275,  0.57682872,  1.28141876, -1.66206553]])

In [59]:
ran(5)

array([ 0.2676633 , -0.82223143,  1.34417107, -0.13236245, -0.27061195])

In [60]:
np.random.randint(10,50)

40

In [63]:
# joining numpy arrays 
#1 -d array
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])


In [64]:
arr = np.concatenate((arr1,arr2))

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# 2-d arrays
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr1
arr2

array([[5, 6],
       [7, 8]])

In [67]:
arr1

array([[1, 2],
       [3, 4]])

In [68]:
arr2

array([[5, 6],
       [7, 8]])

In [69]:
arr = np.concatenate((arr1, arr2))

In [70]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
arr.reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
arr = np.concatenate((arr1, arr2), axis = 1)

In [73]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [76]:
# splitting numpy arrays
arr = np.array([1,2,3,4,5,6])
arr_s = np.array_split(arr, 3)

In [77]:
arr_s

[array([1, 2]), array([3, 4]), array([5, 6])]

In [79]:
arr_s[0]

array([1, 2])

In [82]:
website = "https://docs.scipy.org/doc/numpy/reference/ufuncs.html"
"""
60 universal funcs in numpy library

"""
import webbrowser as wb
wb.open(website)

True